<h1>Aula final sobre algoritmos de ML nao--RNA</h1><hr>

In [ ]:
class Intro(object):
  def __init__(self)->None:
    super().__init__()

  text1 = "Um Contra Todos [One x All] + SoftMax [Nao eh mais a Sigmoide]"
  test2 = "Retorna as probabilidades/chances de uma classe pertencer a cada uma das classes"
  text3 = "Afunçao de custo eh a soft entropy [teoria da informaçao; bits de shannon]"

  @classmethod
  def printaText(cls)->None:
    print(f'{cls.text1}\n\n{cls.test2}\n\n{cls.text3}\n\n'.upper())
    return None
  @staticmethod
  def teoriaBasica()->None:
    stt1 = '{c}'
    stt2 = """
      Mais de duas classes para agrupar/classificar;
      \n\n
      Nao da pra aplicar a regressao logistica de uma maneira pura e simples \n\n
      OneHotEncoding; MultiClass !== Multilabel\n\n
      [Output eh uma unica classe --> multiclass]
        [ex. medcamento que um p'aciente deve tomar]
      [output eh associadoa mais de uma classe ---> Multilabel [ex: uma noticia pode ser associada a mais de uma categoria]]
        [ex. Noticia A--> Economia e Politica]
    """
    sttf = stt1.format(c= stt2)
    print(sttf.upper(), end = '\n\n ###### \n\n')

obj1 = Intro()
print(obj1, end = '\n\n')
Intro.printaText()
Intro.teoriaBasica()


UM CONTRA TODOS [ONE X ALL] + SOFTMAX [NAO EH MAIS A SIGMOIDE]

RETORNA AS PROBABILIDADES/CHANCES DE UMA CLASSE PERTENCER A CADA UMA DAS CLASSES

AFUNÇAO DE CUSTO EH A SOFT ENTROPY [TEORIA DA INFORMAÇAO; BITS DE SHANNON]



      MAIS DE DUAS CLASSES PARA AGRUPAR/CLASSIFICAR;
      


      NAO DA PRA APLICAR A REGRESSAO LOGISTICA DE UMA MANEIRA PURA E SIMPLES 


      ONEHOTENCODING; MULTICLASS !== MULTILABEL


      [OUTPUT EH UMA UNICA CLASSE --> MULTICLASS]
        [EX. MEDCAMENTO QUE UM P'ACIENTE DEVE TOMAR]
      [OUTPUT EH ASSOCIADOA MAIS DE UMA CLASSE ---> MULTILABEL [EX: UMA NOTICIA PODE SER ASSOCIADA A MAIS DE UMA CATEGORIA]]
        [EX. NOTICIA A--> ECONOMIA E POLITICA]
    

 ###### 



In [ ]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

##TRATAMENTO DOS DADOS:

x_numpy = np.array([2,4,3,5,7,2,9,4,10,9,4,6,1,5,6,9,8,3,1,5,6,5,2,7,8,2,5,9,10,2,1,3,8,5,6,5])
y_numpy = np.array([0,0,0,1,2,0,2,0,2,2,0,1,0,1,1,2,1,0,0,1,1,1,0,2,2,0,1,2,2,0,0,0,2,1,1,1])

x = torch.from_numpy(x_numpy.astype(np.float32))
y = torch.from_numpy(y_numpy.astype(np.float32))
y = y.long()
x = x.view(x.shape[0],1)

print(x.shape)
print(y.shape)
print(y)

torch.Size([36, 1])
torch.Size([36])
tensor([0, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 0, 2,
        2, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 1])


In [ ]:
##criaçao do modelo

class RegressaoSoftmax(nn.Module):
  def __init__(self, n_input, n_output)->None:
    super(RegressaoSoftmax, self).__init__()
    self.Linear = nn.Linear(n_input, n_output)
  def foward(self, x):
    return self.Linear(x)

#DEFINIÇAO DE MODELO

input_size = 1
output_size = 3
model = RegressaoSoftmax(input_size, output_size)

#DEFINIÇAO DA FUNÇAO DE CUSTO E OTIMIZADOR

learning_rate = 0.05
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#LOOP DE TREINAMENTO

num_epochs = 1000
contador_custo = []

for epoch in range(num_epochs):
  y_hat = model(x)
  loss = criterion(y_hat, y)
  contador_custo.append(loss)
  loss.backward()

  optimizer.step()

  optimizer.zero_grad()

print("Grafico da funçao de custo".upper())
plt.plot(contador_custo, 'b')
plt.show()

NotImplementedError: Module [RegressaoSoftmax] is missing the required "forward" function

In [13]:
teste = np.array([2,3,6,8,10])
t_teste = torch.from_numpy(teste.astype(np.float32))
t_teste = t_teste.view(t_teste.shape[0], 1)

with torch.no_grad():
  predicoes = model(t_teste)
  print(np.argmax(predicoes, axis=1).flatten()) ##funfou mas a plotagem grafica ta uma bosta :/

tensor([0, 0, 1, 2, 2])


In [ ]:
'''
# RECEITA DE TREINAMENTO
# 1 - DESIGN DO MODELO (INPUT, OUTPUT, FORWARD PASS)
# 2 - DEFINIÇAO DA FUNÇÃO DE CUSTO E OTIMIZADOR
# 3 - LOOP DE TREINAMENTO:
#     - FORWARD PASS: CALCULAR A PREDIÇÃO E O CUSTO
#     - BACKWARPASS: CALCULAR OS GRADIENTES
#     - ATUALIZAR OS PESOS

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

# PREPARAÇÃO DOS DADOS

# Datapoints (NOTAS)
x_numpy = np.array([2,4,3,5,7,2,9,4,10,9,4,6,1,5,6,9,8,3, 1, 5, 6, 5,2, 7, 8, 2,5,9, 10,2,1,3,8,5,6,5])
# 3 classes (0=reprovados, 1=recuperação, 2=aprovados)
y_numpy = np.array([0,0,0,1,2,0,2,0,2,2,0,1,0,1,1,2,1,0,0,1,1,1,0,2,2,0,1,2,2,0,0,0,2,1,1,1])

x = torch.from_numpy(x_numpy.astype(np.float32))
y = torch.from_numpy(y_numpy.astype(np.float32))
y = y.long()
x = x.view(x.shape[0], 1)

print(x.shape)
print(y.shape)
print(y)

# CLASS DE REGRESSÃO LOGÍSTICA

class RegressaoSoftmax(nn.Module):
  def __init__(self, n_input, n_output):
    super(RegressaoSoftmax, self).__init__()
    self.Linear = nn.Linear(n_input, n_output)

  def forward(self, x):
    return self.Linear(x)


# DEFINICIÇÃO DE MODELO
input_size = 1
output_size = 3
model = RegressaoSoftmax(input_size, output_size)

# DEFINIÇÃO DA FUNÇAO DE CUSTO E OTIMIZADOR
learning_rate = 0.05
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# LOOP DE TREINAMENTO
num_epochs = 1000
contador_custo = []
for epoch in range(num_epochs):
  #forward pass and loos
  y_hat = model(x)
  loss = criterion(y_hat, y)
  contador_custo.append(loss)
  #print(y_hat)

  #backward pass (calcular gradientes)
  loss.backward()

  #update (atualizar os pesos)
  optimizer.step()


  #limpar o otimizador
  optimizer.zero_grad()


#contador_custo.detach().numpy()
# PLOTANDO O GRÁFICO DA FUNÇÃO DE CUSTO
print("GRÁFICO DA FUNÇÃO DE CUSTO")
plt.plot(contador_custo.detach(), 'b')
plt.show()

"""#Fazer a predição"""

# fazer predição de teste
teste = np.array([4, 9, 7, 2,6])
t_teste = torch.from_numpy(teste.astype(np.float32))
t_teste = t_teste.view(t_teste.shape[0], 1)

with torch.no_grad():
  predicoes = model(t_teste)
  print (np.argmax(predicoes, axis=1).flatten())
'''


torch.Size([36, 1])
torch.Size([36])
tensor([0, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 0, 2,
        2, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 1])


AttributeError: 'list' object has no attribute 'detach'